[SQLPLUS]
CREATE USER SPRINGMYBATIS IDENTIFIED BY SPRINGMYBATIS;
GRANT CONNECT, RESOURCE TO SPRINGMYBATIS;

[DDL]
CREATE TABLE PERSON (
	PID NUMBER PRIMARY KEY,
	PNAME NVARCHAR2(200),
	PAGE NUMBER
);
CREATE SEQUENCE SEQ_PERSON;